# Generated by Django 6.0.2 on 2026-02-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=80)),
                ('color_code', models.CharField(help_text='Hex color code like #ffffff', max_length=7)),
                ('image', models.ImageField(upload_to='products/variants/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('additional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'), models.Index(fields=['color_name'], name='products_pr_color_n_6870f3_idx')],
                'unique_together': {('product', 'color_name')},
            },
        ),
    ]
