# Generated by Django 6.0.2 on 2026-02-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmiLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("down_payment", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("selected_tenure_months", models.PositiveSmallIntegerField(default=12)),
                ("interest_rate", models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ("emi_chart", models.JSONField(blank=True, default=dict)),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_mobile", models.CharField(max_length=20)),
                ("customer_email", models.EmailField(max_length=254)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emi_leads",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="products_em_created_d5fdb5_idx"),
                    models.Index(fields=["customer_mobile", "created_at"], name="products_em_custome_df6f58_idx"),
                    models.Index(fields=["customer_email", "created_at"], name="products_em_custome_2978cc_idx"),
                ],
            },
        ),
    ]
