# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_emilead"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emilead",
            old_name="products_em_created_d5fdb5_idx",
            new_name="products_em_created_f68135_idx",
        ),
        migrations.RenameIndex(
            model_name="emilead",
            old_name="products_em_custome_df6f58_idx",
            new_name="products_em_custome_ce975d_idx",
        ),
        migrations.RenameIndex(
            model_name="emilead",
            old_name="products_em_custome_2978cc_idx",
            new_name="products_em_custome_c8b6da_idx",
        ),
    ]
