# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
