# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_shippingaddress_gst_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="business_invoice_required",
            field=models.BooleanField(default=False),
        ),
    ]
