# Generated by Django 6.0.2 on 2026-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingaddress_business_invoice_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], db_index=True, default='online', max_length=20),
        ),
    ]
