# Generated by Django 6.0.2 on 2026-02-24 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0003_shippingaddress_business_invoice_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('warranty_card_number', models.CharField(max_length=60)),
                ('product_name', models.CharField(max_length=180)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_wa_user_id_c65871_idx'), models.Index(fields=['created_at'], name='accounts_wa_created_020a9f_idx')],
            },
        ),
    ]
