# Generated by Django 6.0.2 on 2026-02-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_cartit_cart_id_4bd8c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product', 'variant'], name='cart_cartit_cart_id_bddf3b_idx'),
        ),
    ]
