# Generated by Django 6.0.2 on 2026-02-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('heading', models.CharField(max_length=220)),
                ('subheading', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/sections/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('image', models.ImageField(upload_to='home/features/')),
                ('card_type', models.CharField(choices=[('large', 'Large'), ('small', 'Small')], default='small', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'card_type', 'order'], name='core_homefe_is_acti_889cc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='home/hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_homehe_is_acti_cc54a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeModeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=220)),
                ('image', models.ImageField(upload_to='home/modes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_homemo_is_acti_41208c_idx')],
            },
        ),
    ]
