# Generated by Django 6.0.2 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contactinquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="home/testimonials/"),
        ),
    ]
