# Generated by Django 6.0.2 on 2026-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homesectionconfig',
            index=models.Index(fields=['is_active', 'key'], name='core_homese_is_acti_2620dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sitecontent',
            index=models.Index(fields=['is_active', 'key'], name='core_siteco_is_acti_a1a93c_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_active', 'created_at'], name='core_testim_is_acti_d9b2d7_idx'),
        ),
    ]
