# Generated by Django 6.0.2 on 2026-02-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('excerpt', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug', 'is_published'], name='blog_blogpo_slug_c2a5f8_idx')],
            },
        ),
    ]
