# Generated by Django 6.0.2 on 2026-03-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_battery_guide'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'published_at'], name='blog_blogpo_is_publ_dcd2a8_idx'),
        ),
    ]
